/* file generated by gperf.sh (in turn using gperf) */

#ifndef GPERF_TT_NATIONWIDE_H
#define GPERF_TT_NATIONWIDE_H

/* included code from gperf input file declaration section */
#include "banks.h"
/* end of included code */

/* gperf lookup function */
const char *
nationwide_transaction_type_lookup(register const char *, register size_t);

#endif
